# Generated by Django 3.0 on 2019-12-03 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('code', models.CharField(max_length=3, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=52)),
                ('continent', models.CharField(choices=[('Asia', 'Asia'), ('Europe', 'Europe'), ('North America', 'North America'), ('Africa', 'Africa'), ('Oceania', 'Oceania'), ('Antarctica', 'Antarctica'), ('South America', 'South America')], default='Asia', max_length=13)),
                ('region', models.CharField(max_length=45)),
                ('surface_area', models.FloatField()),
                ('indep_year', models.SmallIntegerField()),
                ('population', models.IntegerField()),
                ('life_expectancy', models.FloatField()),
                ('gnp', models.FloatField()),
                ('gnp_old', models.FloatField()),
                ('local_name', models.CharField(max_length=45)),
                ('government_form', models.CharField(max_length=45)),
                ('head_of_state', models.CharField(max_length=60)),
                ('capital', models.IntegerField()),
                ('code2', models.CharField(max_length=2)),
            ],
            options={
                'db_table': 'country',
            },
        ),
        migrations.CreateModel(
            name='Languages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=30)),
                ('is_official', models.CharField(choices=[('T', 'T'), ('F', 'F')], default='F', max_length=2)),
                ('percentage', models.FloatField(default='0.0')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='country.Country')),
            ],
            options={
                'db_table': 'country_languages',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35)),
                ('district', models.CharField(max_length=20)),
                ('population', models.IntegerField()),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='country.Country')),
            ],
            options={
                'db_table': 'city',
            },
        ),
    ]
