# Generated by Django 3.0 on 2019-12-04 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='indep_year',
            field=models.SmallIntegerField(null=True),
        ),
    ]
