# Generated by Django 3.0 on 2019-12-04 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0002_auto_20191204_0338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='life_expectancy',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='population',
            field=models.IntegerField(null=True),
        ),
    ]
