# Generated by Django 3.0 on 2019-12-04 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0003_auto_20191204_0339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='local_name',
            field=models.CharField(max_length=45, null=True),
        ),
    ]
