# Generated by Django 3.0 on 2019-12-04 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0004_auto_20191204_0342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='capital',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='country',
            name='code2',
            field=models.CharField(default='', max_length=2),
        ),
        migrations.AlterField(
            model_name='country',
            name='gnp',
            field=models.FloatField(default=None),
        ),
        migrations.AlterField(
            model_name='country',
            name='gnp_old',
            field=models.FloatField(default=None),
        ),
        migrations.AlterField(
            model_name='country',
            name='government_form',
            field=models.CharField(default='', max_length=45),
        ),
        migrations.AlterField(
            model_name='country',
            name='head_of_state',
            field=models.CharField(default=None, max_length=60),
        ),
        migrations.AlterField(
            model_name='country',
            name='indep_year',
            field=models.SmallIntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='country',
            name='life_expectancy',
            field=models.FloatField(default=None),
        ),
        migrations.AlterField(
            model_name='country',
            name='local_name',
            field=models.CharField(default='', max_length=45),
        ),
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(default='', max_length=52),
        ),
        migrations.AlterField(
            model_name='country',
            name='population',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='country',
            name='region',
            field=models.CharField(default='', max_length=45),
        ),
        migrations.AlterField(
            model_name='country',
            name='surface_area',
            field=models.FloatField(default='0.00'),
        ),
    ]
