# Generated by Django 3.0 on 2019-12-04 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0006_auto_20191204_0349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='code2',
            field=models.CharField(default='', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='gnp_old',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='government_form',
            field=models.CharField(default='', max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='indep_year',
            field=models.SmallIntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='local_name',
            field=models.CharField(default='', max_length=45, null=True),
        ),
    ]
