# Generated by Django 3.0 on 2019-12-04 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0007_auto_20191204_0350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='life_expectancy',
            field=models.FloatField(default=None, null=True),
        ),
    ]
