# Generated by Django 3.0 on 2019-12-04 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0008_auto_20191204_0351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='gnp',
            field=models.FloatField(default=None, null=True),
        ),
    ]
