# Generated by Django 3.0 on 2019-12-04 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0009_auto_20191204_0352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='capital',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='head_of_state',
            field=models.CharField(default=None, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='region',
            field=models.CharField(default='', max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='surface_area',
            field=models.FloatField(default='0.00', null=True),
        ),
    ]
